### ISSUE TITLE
Changing `setup.style` does nothing

### ISSUE THREAD

**Issue by strash** [cdmill/neomodern.nvim#13]
The iceclimber is the only theme I can see and the daylight if I change the background to "light".

**Comment by strash** [comment]
But I can toggle them with `setup.toggle_style_key` after last update.

**Comment by cdmill** [comment]
What does your config look like? Because I'm able to change styles on mine. For reference, my config is below:

```lua
    config = function()
      require("neomodern").setup({
        style = "iceclimber",
        toggle_style_key = "<leader>cc",
        code_style = {
          headings = "none",
        },
        ui = {
          plain = true,
          show_eob = false,
          -- colored_docstrings = false,
          telescope = "borderless",
        },
      })
      require("neomodern").load()
    end,

```

**Comment by strash** [comment]
```lua
require("neomodern").setup({
	style = "iceclimber", -- iceclimber, coffeecat, darkforest, campfire, roseprime, daylight
	toggle_style_key = "<leader>bm",
})
require("neomodern").load()
```

It looks like this. But no matter what style I set the theme is always `iceclimber`.

**Comment by cdmill** [comment]
Comment out line 119 in `strash/.dotfiles/nvim/.config/nvim/lua/settings.lua`. Calling `neomodern.load()` with already call `set colorscheme` with your selected style. If you call `set colorscheme neomodern` it defaults to `iceclimber` which is where your trouble is coming from. I'll add a note about this in the readme

**Comment by strash** [comment]
Oh I see, thanks you!
