### ISSUE TITLE
cmp settings

### ISSUE THREAD

**Issue by koenverburg** [cdmill/neomodern.nvim#22]
Hi, love the plugin. However, How can I turn off the styling on cmp?
<img width="457" alt="image" src="https://github.com/user-attachments/assets/ccba2e68-45ee-4b2c-86fd-86a635f0d174">

**Comment by cdmill** [comment]
Great to hear. By turn off the styling do you mean make your cmp look like the image you attached?

For reference, my cmp looks like this:
<img width="413" alt="sc 2024-07-25 at 09 14 24" src="https://github.com/user-attachments/assets/ebb0f1ea-05e1-4b75-8637-27887e2a1f35">

**Comment by koenverburg** [comment]
Interesting, because when I disable neomodern and use no-clown-fiesta and others. I have it set to

<img width="728" alt="image" src="https://github.com/user-attachments/assets/01b08fbd-fc6d-4d75-acab-d41435da48e9">

**Comment by cdmill** [comment]
Interesting. Let me see if I can figure out what's going on and I'll ping you once I do

**Comment by cdmill** [comment]
@koenverburg I just pushed a commit that should fix this issue. I ended up setting the FloatBorder highlight differently. If you ever want to customize it yourself in the future you could always overwrite the highlight in your neomodern config

**Comment by koenverburg** [comment]
Yes, the borders are showing. Thanks!

**Comment by cdmill** [comment]
@koenverburg btw I liked the look no-clown-fiestas cmp ui so I just added a few more opts if you're wanting something similar:

```lua
require("neomodern").setup({
-- snip --
  ui = {
    plain_float = true, -- don't set background of floating windows. recommended for when using floating windows with borders
    cmp = {
      plain = true, --don't highlight lsp-kind items
    },
   }
})
```

**Comment by koenverburg** [comment]
@cdmill this looks even better! Thanks!
