### ISSUE TITLE
Disable special handling for `defaultLibrary`

### ISSUE THREAD

**Issue by GoldsteinE** [cdmill/neomodern.nvim#28]
Hi!

I’d like to disable special highlights for `defaultLibrary` tokens. I don’t really care where a functions comes from and it looks kinda confusing. I’m not sure how would I do that though: I’ve tried setting

```lua
['@lsp.typemod.function.defaultLibrary'] = {}
```

or

```lua
['@lsp.typemod.function.defaultLibrary'] = { guifg = 'none' }
```

or

```lua
['@lsp.typemod.function.defaultLibrary'] = { link = 'None' }
```

but that just causes an info message about this highlight to appear at startup and the special coloring still applies. How do I override this?

**Comment by cdmill** [comment]
Should be `["@lsp.typemod.function.defaultLibrary"] = { fg = "none" }`. Note `fg = "none"` instead if `guifg = "none"`
